sonar.projectKey=juansrg95_ReservaCanchaF
sonar.organization=juansrg95
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.junit.reportPaths=build/test-results/test
