# Identificación del proyecto en SonarCloud
sonar.projectKey=juansrg95_ReservaCanchaF
sonar.organization=juansrg95
sonar.host.url=https://sonarcloud.io

# Código y tests
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main

# Resultados de tests (JUnit)
sonar.junit.reportPaths=build/test-results/test

# Cobertura con JaCoCo (usar SOLO el XML)
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# Codificación
sonar.sourceEncoding=UTF-8

