# Identificación del proyecto en SonarCloud
sonar.projectKey=juansrg95_ReservaCanchaF
sonar.organization=juansrg95
sonar.host.url=https://sonarcloud.io

# Código y tests
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main

# Resultados de tests
sonar.junit.reportPaths=build/test-results/test

# Reporte de cobertura JaCoCo (muy importante)
sonar.jacoco.reportPaths=build/jacoco/test.exec
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# Codificación
sonar.sourceEncoding=UTF-8
