
spring.application.name=ReservaCanchaF

# PostgreSQL (para ejecuciÃ³n local; no se usa en tests)
spring.datasource.url=jdbc:postgresql://localhost:5432/reservas
spring.datasource.username=postgres
spring.datasource.password=S3b4st14n

spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Muestra el mensaje de error en la respuesta
server.error.include-message=always
# Muestra el stacktrace si lo pides con ?trace=true
server.error.include-stacktrace=on_param
# (opcional) incluye errores de binding/validación
server.error.include-binding-errors=always


server.port=8081

# Actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never


