ALTER TABLE usuario ADD COLUMN IF NOT EXISTS email  VARCHAR(255) NOT NULL DEFAULT 'admin@demo.com';
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS nombre VARCHAR(255) NOT NULL DEFAULT 'Administrador';
ALTER TABLE usuario ALTER COLUMN email  DROP DEFAULT;
ALTER TABLE usuario ALTER COLUMN nombre DROP DEFAULT;
