name: CI

on:
  push:
    branches: [ develop, 'feature/**' ]
  pull_request:
    branches: [ develop, main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      #  Primero pruebas + cobertura (genera el XML)
      - name: Tests + JaCoCo
        run: ./gradlew clean test jacocoTestReport --no-daemon

      # (Opcional) Subir reportes para inspección
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            build/test-results/test
            build/reports/tests/test
            build/reports/jacoco/test

      # Ahora sí: análisis en SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.junit.reportPaths=build/test-results/test
            -Dsonar.java.binaries=build/classes/java/main






